"""empty message

Revision ID: 418232f6a224
Revises: f9936947e10
Create Date: 2015-06-30 13:05:38.624791

"""

# revision identifiers, used by Alembic.
revision = '418232f6a224'
down_revision = 'f9936947e10'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
