"""empty message

Revision ID: 7c77df778d5
Revises: 418232f6a224
Create Date: 2015-06-30 14:43:16.979866

"""

# revision identifiers, used by Alembic.
revision = '7c77df778d5'
down_revision = '418232f6a224'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_creations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_creations')
    ### end Alembic commands ###
