"""empty message

Revision ID: 8c9ee68e96f
Revises: 281ff90b6948
Create Date: 2015-06-27 17:33:01.011436

"""

# revision identifiers, used by Alembic.
revision = '8c9ee68e96f'
down_revision = '281ff90b6948'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_column('users', 'location')
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'created')
    op.drop_column('users', 'bio')
    ### end Alembic commands ###
